# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTaskEdit(object):
    def setupUi(self, FormTaskEdit):
        FormTaskEdit.setObjectName("FormTaskEdit")
        FormTaskEdit.resize(653, 305)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormTaskEdit)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(FormTaskEdit)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 481, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_task = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.verticalLayout_2.addWidget(self.lineEdit_task)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_2.addWidget(self.dateTimeEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_okay = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_okay.setObjectName("pushButton_okay")
        self.horizontalLayout_2.addWidget(self.pushButton_okay)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(FormTaskEdit)
        QtCore.QMetaObject.connectSlotsByName(FormTaskEdit)

    def retranslateUi(self, FormTaskEdit):
        _translate = QtCore.QCoreApplication.translate
        FormTaskEdit.setWindowTitle(_translate("FormTaskEdit", "Изменить задачу"))
        self.groupBox.setTitle(_translate("FormTaskEdit", "Изменить задачу"))
        self.label.setText(_translate("FormTaskEdit", "Описание задачи"))
        self.label_2.setText(_translate("FormTaskEdit", "Время"))
        self.pushButton.setText(_translate("FormTaskEdit", "Отменить"))
        self.pushButton_okay.setText(_translate("FormTaskEdit", "Ok"))
